base.uri=https://restful-booker.herokuapp.com
base.path=

api.post.auth=/auth

api.get.bookings=/booking
api.post.booking=/booking

api.get.booking=/booking/{id}
api.put.booking=/booking/{id}
api.patch.booking=/booking/{id}
api.delete.booking=/booking/{id}